apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fridgefreak
    type: backend
  name: fridgefreak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fridgefreak
      type: backend
  template:
    metadata:
      labels:
        app: fridgefreak
        type: backend
    spec:
      imagePullSecrets: 
        - name: regcred
      containers:
        - env:
            - name: DEV_CLEVER_CLOUD_DB
              valueFrom:
                configMapKeyRef:
                  key: DEV_CLEVER_CLOUD_DB
                  name: config-backend
            - name: DEV_CLEVER_CLOUD_HOST
              valueFrom:
                configMapKeyRef:
                  key: DEV_CLEVER_CLOUD_HOST
                  name: config-backend
            - name: DEV_CLEVER_CLOUD_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DEV_CLEVER_CLOUD_PASSWORD
                  name: secrets-backend
            - name: DEV_CLEVER_CLOUD_PORT
              valueFrom:
                configMapKeyRef:
                  key: DEV_CLEVER_CLOUD_PORT
                  name: config-backend
            - name: DEV_CLEVER_CLOUD_USER
              valueFrom:
                configMapKeyRef:
                  key: DEV_CLEVER_CLOUD_USER
                  name: config-backend
            - name: DEV_DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  key: DEV_DATABASE_HOST
                  name: config-backend
            - name: DEV_DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  key: DEV_DATABASE_NAME
                  name: config-backend
            - name: DEV_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DEV_DATABASE_PASSWORD
                  name: secrets-backend
            - name: DEV_DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  key: DEV_DATABASE_PORT
                  name: config-backend
            - name: DEV_DATABASE_USER
              valueFrom:
                configMapKeyRef:
                  key: DEV_DATABASE_USER
                  name: config-backend
            - name: DEV_TABLE_NAME
              valueFrom:
                configMapKeyRef:
                  key: DEV_TABLE_NAME
                  name: config-backend
            - name: ENV_STATE
              valueFrom:
                configMapKeyRef:
                  key: ENV_STATE
                  name: config-backend
            - name: TEST_DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  key: TEST_DATABASE_HOST
                  name: config-backend
            - name: TEST_DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  key: TEST_DATABASE_NAME
                  name: config-backend
            - name: TEST_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: TEST_DATABASE_PASSWORD
                  name: secrets-backend
            - name: TEST_DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  key: TEST_DATABASE_PORT
                  name: config-backend
            - name: TEST_DATABASE_USER
              valueFrom:
                configMapKeyRef:
                  key: TEST_DATABASE_USER
                  name: config-backend
            - name: TEST_TABLE_NAME
              valueFrom:
                configMapKeyRef:
                  key: TEST_TABLE_NAME
                  name: config-backend
            - name: WAIT_HOSTS
              value: mysql-svc:3306
            - name: WAIT_HOST_CONNECT_TIMEOUT
              value: "1"
          image: ghcr.io/dgrzelec/fridgefreak-app:0.1-alpine
          imagePullPolicy: Always
          name: fridgefreak-app
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          volumeMounts:
          - name: config-backend
            mountPath: /config
          - name: secrets-backend
            mountPath: /secrets
          ports:
            - containerPort: 8000
              protocol: TCP
      volumes:  
      - name: config-backend # needed for kustomization configmap generator
        configMap:
          name: config-backend
      - name: secrets-backend # needed for kustomization secret generator
        secret:
          secretName: secrets-backend