apiVersion: v1
kind: Service
metadata:
  labels:
    app: fridgefreak
    type: backend
  name: fridgefreak
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    app: fridgefreak
    type: backend
