namespace: fridgefreak
commonLabels:
  stage: dev
# resources:
  # - mysql-setup-configmap.yaml
  # - fridgefreak-service.yaml
  # - mysql-service.yaml
  # - mysql-fridgefreak-persistentvolumeclaim.yaml
  # - mysql-deployment.yaml
  # - fridgefreak-deployment.yaml

configMapGenerator:
  - name: config-backend
    envs:
      - config.env
secretGenerator:
  - name: secrets-backend
    envs:
      - secret.env
  # - name: regcred
  #   envs:
  #     - regcred.env
generatorOptions:
  disableNameSuffixHash: true
        