apiVersion: v1
kind: Service
metadata:
  labels:
    app: fridgefreak
    type: database
  name: mysql
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    app: fridgefreak
    type: database
