apiVersion: v1
data:
  fridgefreak_schema.sh: >
    mysql ${mysql_flags} -e
    "create database if not exists fridgefreak;
    use fridgefreak;

    CREATE TABLE IF NOT EXISTS products (
    id int NOT NULL AUTO_INCREMENT,
    name text,
    quantity int DEFAULT NULL,
    category text,
    storage_space text,
    expire_by date DEFAULT NULL,
    PRIMARY KEY (id)
    );

    CREATE TABLE IF NOT EXISTS test_products LIKE products;

    TRUNCATE test_products;"
  
  users.sh: >
    mysql ${mysql_flags} -e
    "CREATE USER IF NOT EXISTS 'testuser' IDENTIFIED WITH mysql_native_password BY '${TEST_DATABASE_PASSWORD}';
    GRANT ALL privileges on fridgefreak.test_products TO 'testuser';
    CREATE USER IF NOT EXISTS 'fridgefreak_api' IDENTIFIED WITH mysql_native_password BY '${DEV_DATABASE_PASSWORD}';
    GRANT ALL privileges on fridgefreak.products TO 'fridgefreak_api';"
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    app: fridgefreak
    type: database
  name: mysql-setup
