apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    app: fridgefreak
    type: volume
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  # claimRef:
  #   # namespace: fridgefreak
  #   name: mysql-pv
  hostPath:
    path: "/mnt/data/mysql"