apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.globals.labels.app}}
    type: {{ .Values.fridgefreak.labels.type}}
  name: fridgefreak
spec:
  ports:
    - name: "{{ .Values.fridgefreak.port}}"
      port: {{ .Values.fridgefreak.port}}
      targetPort: {{ .Values.fridgefreak.port}}
  selector:
    app: {{ .Values.globals.labels.app}}
    type: {{ .Values.mysql.labels.type}}
