apiVersion: batch/v1
kind: Job
metadata:
  name: db-sync
  annotations:
    "helm.sh/hook": post-install
  labels:
    app: {{ .Values.globals.labels.app}}
spec:  
  activeDeadlineSeconds: 1800 
  backoffLimit: 2  
  template:         
    metadata:
      name: db-sync
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: db-sync
        image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag}}"
        command: 
          - sh  
          - "-c"
          - >
            mysqldump --no-create-info --no-tablespaces --compact --set-gtid-purged=OFF --single-transaction --skip-extended-insert 
            -u $DEV_CLEVER_CLOUD_USER -p$DEV_CLEVER_CLOUD_PASSWORD -h $DEV_CLEVER_CLOUD_HOST
            $DEV_CLEVER_CLOUD_DB $DEV_CLEVER_CLOUD_TABLE > fridgefreak-table.sql;
            echo "FILE CONTENT:";
            cat fridgefreak-table.sql;
            echo "INSERTING DATA:";
            mysql -u root -p$MYSQL_ROOT_PASSWORD -h $DEV_DATABASE_HOST --force
            $DEV_DATABASE_NAME < fridgefreak-table.sql;
            echo "DONE!";

        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: MYSQL_ROOT_PASSWORD 
                name: {{ .Values.secrets.backend}}
          - name: DEV_CLEVER_CLOUD_DB
            valueFrom:
              configMapKeyRef:
                key: DEV_CLEVER_CLOUD_DB
                name: {{ .Values.configMaps.backend}}
          - name: DEV_CLEVER_CLOUD_HOST
            valueFrom:
              configMapKeyRef:
                key: DEV_CLEVER_CLOUD_HOST
                name: {{ .Values.configMaps.backend}}
          - name: DEV_CLEVER_CLOUD_PASSWORD
            valueFrom:
              secretKeyRef:
                key: DEV_CLEVER_CLOUD_PASSWORD
                name: {{ .Values.secrets.backend}}
          - name: DEV_CLEVER_CLOUD_PORT
            valueFrom:
              configMapKeyRef:
                key: DEV_CLEVER_CLOUD_PORT
                name: {{ .Values.configMaps.backend}}
          - name: DEV_CLEVER_CLOUD_USER
            valueFrom:
              configMapKeyRef:
                key: DEV_CLEVER_CLOUD_USER
                name: {{ .Values.configMaps.backend}}
          - name: DEV_CLEVER_CLOUD_TABLE
            valueFrom:
              configMapKeyRef:
                key: DEV_CLEVER_CLOUD_TABLE
                name: {{ .Values.configMaps.backend}}
          - name: DEV_DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                key: DEV_DATABASE_HOST
                name: {{ .Values.configMaps.backend}}
          - name: DEV_DATABASE_NAME
            valueFrom:
              configMapKeyRef:
                key: DEV_DATABASE_NAME
                name: {{ .Values.configMaps.backend}}
          - name: DEV_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                key: DEV_DATABASE_PASSWORD
                name: {{ .Values.secrets.backend}}
          - name: DEV_DATABASE_PORT
            valueFrom:
              configMapKeyRef:
                key: DEV_DATABASE_PORT
                name: {{ .Values.configMaps.backend}}
          - name: DEV_DATABASE_USER
            valueFrom:
              configMapKeyRef:
                key: DEV_DATABASE_USER
                name: {{ .Values.configMaps.backend}}
          - name: DEV_TABLE_NAME
            valueFrom:
              configMapKeyRef:
                key: DEV_TABLE_NAME
                name: {{ .Values.configMaps.backend}}
      restartPolicy: OnFailure
