apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: {{ .Values.globals.labels.app}}
    type: {{ .Values.mysql.labels.type}}
  name: {{ .Values.mysql.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.globals.labels.app}}
      type: {{ .Values.mysql.labels.type}}
  serviceName: mysql-svc
  template:
    metadata:
      labels:
        app: {{ .Values.globals.labels.app}}
        type: {{ .Values.mysql.labels.type}}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: {{ .Values.secrets.backend}}
            - name: DEV_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DEV_DATABASE_PASSWORD
                  name: {{ .Values.secrets.backend}}
            - name: TEST_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: TEST_DATABASE_PASSWORD
                  name: {{ .Values.secrets.backend}}
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag}}"
          name: mysql-db-pod
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/app-root/src/mysql-init/1.sh
              name: mysql-setup
              subPath: 1.sh
            - mountPath: /opt/app-root/src/mysql-init/2.sh
              name: mysql-setup
              subPath: 2.sh
            - mountPath: /var/lib/mysql
              name: mysql-vc
          # resources:
          #   requests:
          #     memory: "64Mi"
          #     cpu: "250m"
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
      hostname: mysql
      volumes: # is this section needed with helm?
        - configMap:
            items:
              - key: fridgefreak_schema.sh
                path: 1.sh
              - key: users.sh
                path: 2.sh
            name: mysql-setup
          name: mysql-setup
        - name: {{ .Values.secrets.backend}} # needed for kustomization secret generator
          secret:
            secretName: {{ .Values.secrets.backend}}
  volumeClaimTemplates:
    - metadata:
       name: mysql-vc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
        storageClassName: lvms-vg1
